### ISSUE TITLE
List of themes in dark mode

### ISSUE THREAD

**Issue by LKezHn** [mrLuisFer/seo-generator#11]
In the dark mode the background color of the theme's list is white, however the text is also white

**Comment by mrluisfer** [comment]
Yup, it is something that is already being resolved, since as it is an external component, it is still necessary to add custom styles

**Comment by mrluisfer** [comment]
Done, now it's fixed in Commit [670e981](https://github.com/mrLuisFer/seo-generator/commit/670e9810141dbd02e26082d5487cff4aa4db464d) ;)
